#!/usr/bin/env python

"""
    title:      pyscreenie
    
    date:       3.21.2010
    
    author:     Lupine  - http://www.thelupine.com
    
    description:    Python/GTK/Glade app to capture a screenshot of your desktop.
    
"""

import sys, os, glob, signal, time, re, sqlite3, pexpect
from subprocess import Popen, PIPE
from gi.repository import Gtk
     
APPNAME     = "pyscreenie"
APPVERSION  = "1.9.5"
APPCONFDIR  = os.environ["HOME"] + '/.pyscreenie'
GLADE_FILE  = "/usr/share/pyscreenie/pyscreenie.glade"
SCHEDULER   = 'pyscreenie-scheduler'
PIDFILE     = APPCONFDIR + '/pyscreenie.pid'
CONFIGFILE  = APPCONFDIR + "/config.db"

print "\n\n" + APPNAME + " version " + APPVERSION + ", Copyright (C) 2008 - TheLupine"
print APPNAME + " comes with ABSOLUTELY NO WARRANTY, is licensed under the"
print "GNU GENERAL PUBLIC LICENSE and is free and open source software."
print "http://www.thelupine.com\n\n"

##check for config dir and if needed, create it
if not os.path.isdir(APPCONFDIR):
    try:
        os.mkdir(APPCONFDIR)
    except:
        print "Unable to create config dir " + APPCONFDIR
        sys.exit(1)

class pyscreenie:
    def startupcleanup(self):
        """This function will remove any existing PID or conf files"""
        self.clear_conf_files()
        self.stop_child()

    def spawn_child(self, datestamp, location, desktopsize, pngorjpg, starttime, repeat):
        """This function will spawn the child process"""
        child = Popen([SCHEDULER] + [datestamp] + [location] + [desktopsize] + [pngorjpg] + [starttime] + [repeat])
        pidfile = open(PIDFILE, 'w')
        pidfile.write(str(child.pid))

    def stop_child(self):
        """This function will stop the child process"""
        if os.path.isfile(PIDFILE):
            pidfile = open(PIDFILE, 'r')
            pidnum = pidfile.read()
            if not pidnum == '':
                try:
                    os.kill(int(pidnum), signal.SIGUSR1)
                except OSError:
                    pass
            os.unlink(PIDFILE)

    def on_png_radiobutton_clicked(self, widget):
        """This function will set the compression and spinbutton sensitive to false"""
        self.label_compression.set_sensitive(False)
        self.jpgcompression_spinbutton.set_sensitive(False)
    
    def on_jpg_radiobutton_clicked(self, widget):
        """This function will set the compression and spinbutton sensitive to true"""
        self.label_compression.set_sensitive(True)
        self.jpgcompression_spinbutton.set_sensitive(True)
        
    def on_about_menu_activate(self, widget, data=None):
        """This will show the ABOUT dialog"""
        self.version_label.set_markup('<span weight="bold" size="larger"> ' + \
                                                            APPNAME + ' ' + \
                                                            'v' + APPVERSION + \
                                                            '</span>')
        self.about_dialog.present()
        
    def on_about_dialog_delete_event(self, widget, event=None):
        """This will close the ABOUT dialog"""
        self.about_dialog.hide()
        return True    

    def on_enable_togglebutton_toggled(self, widget):
        """This function will enable/disable the scheduler"""
        if self.enable_togglebutton.get_active() == True:
            self.enable_togglebutton.set_label('_Enabled')
            datestamp = time.strftime("%H%M%S%d%m%Y", time.localtime())
                
            #create the date process file
            datestampfile = open(APPCONFDIR + '/pyscreenie-' + datestamp + '.conf', 'w')
            datestampfile.close()

            #get screenie location
            savepath = self.savepath_filechooserbutton.get_uri()
            location = savepath.replace('file://','')
            
            #get desktop size
            desktopsize = self.desktopsize_comboboxtext_entry.get_text()
            
            #png or jpg?
            pngorjpg = ''
            getcomp = ''
            if self.png_radiobutton.get_active():
                pngorjpg = 'png'
                filetype = 'png'
            elif self.jpg_radiobutton.get_active():
                getcomp = self.jpgcompression_spinbutton.get_text()
                filetype = 'jpg'
                pngorjpg = 'jpg' + getcomp
                
            #when to grab the screenie (and if repeating, when to begin)
            starthour = self.starthour_spinbutton.get_text()
            if int(starthour) < 10:
                starthour = "0%s" % (starthour)
            startmin = self.startmin_spinbutton.get_text()
            if int(startmin) < 10:
                startmin = "0%s" % (startmin)
            starttime = "%s%s" % (starthour, startmin)
            
            #if repeating, how often
            if self.repeat_none_radiobutton.get_active():
                repeat = 'none'
            if self.repeat_min_radiobutton.get_active():
                repeat = 'minute'
            elif self.repeat_hour_radiobutton.get_active():
                repeat = 'hour'
            elif self.repeat_day_radiobutton.get_active():
                repeat = 'day'
            elif self.repeat_week_radiobutton.get_active():
                repeat = 'week'

            #spawn the process
            self.spawn_child(datestamp, location, desktopsize, pngorjpg, starttime, repeat)
            
            #update the CONFIGFILE
            self.update_configfile(savepath, desktopsize, filetype, getcomp, starthour, startmin, repeat)
            
            #minimize the main dialog
            self.prefs_dialog.iconify()
        else:
            self.enable_togglebutton.set_label('_Enable')
            self.clear_conf_files()
            self.stop_child()

    def clear_conf_files(self):
        """This function will remove all conf files"""
        filelist = os.listdir(APPCONFDIR + '/')
        for listedfile in filelist:
            if re.search('.conf', listedfile):
                os.unlink(APPCONFDIR + '/' + listedfile)
    
    def main_quit(self, action):
        """This function will clean up everything and properly quit"""
        self.clear_conf_files()
        self.stop_child()
        Gtk.main_quit()

    def check_sqlitedb(self):
        """
        This function will check for the sqlite3 file, and if not exist
        it will create it.  If it does exist, it will perform any DB
        updates that are needed.
        """
        if os.path.isfile(CONFIGFILE):
            sqlconn = sqlite3.connect(CONFIGFILE)
            sqlcursor = sqlconn.cursor()
            sqlcursor.execute('''pragma table_info('options')''')
            """
            # this is what the current schema should look like
            0|id|int|0||0
            2|savepath|text|0||0
            3|desktopsize|text|0||0
            4|filetype|text|0||0
            5|compression|int|0||0
            6|hour|int|0||0
            7|minute|int|0||0
            8|repeat|text|0||0
            """
        else:
            try:
                sqlite3.connect(CONFIGFILE)
            except:
                errormessage = 'Unable to connect to sqlite3 file:\n' \
                                + CONFIGFILE + \
                                '\nYou will not be able to save config options.\n\n'
                print errormessage
            else:
                sqlconn = sqlite3.connect(CONFIGFILE)
                sqlcursor = sqlconn.cursor()
                sqlcursor.execute('''create table if not exists options
                                        (id int,
                                        savepath text, 
                                        desktopsize text,
                                        filetype text, 
                                        compression int,
                                        hour int,
                                        minute int,
                                        repeat text)''')
                sqlconn.commit()
                sqlcursor.execute('''INSERT INTO options VALUES (?,?,?,?,?,?,?,?)
                                    ''',("0","","Full Desktop","png","0","0","0","min") )
                sqlconn.commit()
                sqlconn.close

    def read_configfile(self):
        """
        This function will read in the settings from the sqlite
        CONFIGFILE file, and populate the necessary values
        """
        savepath = ""
        desktopsize = ""
        filetype = ""
        compression = ""
        hour = ""
        minute = ""
        repeat = ""
        
        sqlconn = sqlite3.connect(CONFIGFILE)
        sqlcursor = sqlconn.cursor()
        #first look through the sqlite db, and assign values to variables
        for row in sqlcursor.execute("SELECT * FROM options"):
            if (row[1]):
                savepath = row[1]
                self.savepath_filechooserbutton.set_uri(savepath)

            if (row[2]):
                desktopsize = str(row[2])
                self.desktopsize_comboboxtext_entry.set_text(desktopsize)
                
            if (row[3]):
                filetype = row[3]
                if filetype == "png":
                    self.png_radiobutton.set_active(1)
                if filetype == "jpg":
                    self.jpg_radiobutton.set_active(1)
                    self.label_compression.set_text(compression)
                
            if (row[4]):
                compression = str(row[4])
                self.jpgcompression_spinbutton.set_text(compression)
                
            if (row[5]):
                hour = str(row[5])
                self.starthour_spinbutton.set_text(hour)
            
            if (row[6]):
                minute = str(row[6])
                self.startmin_spinbutton.set_text(minute)

            if (row[7]):
                repeat = row[7]
                if repeat == "none":
                    self.repeat_none_radiobutton.set_active(1)
                if repeat == "min":
                    self.repeat_min_radiobutton.set_active(1)
                if repeat == "hour":
                    self.repeat_hour_radiobutton.set_active(1)
                if repeat == "day":
                    self.repeat_day_radiobutton.set_active(1)
                if repeat == "week":
                    self.repeat_week_radiobutton.set_active(1)

    def update_configfile(self,savepath,desktopsize,filetype,compression,hour,minute,repeat):
        """
        This function will update the CONFIGFILE file
        """
        sqlconn = sqlite3.connect(CONFIGFILE)
        sqlcursor = sqlconn.cursor()
        values = (savepath,desktopsize,filetype,compression,hour,minute,repeat,"0")
        sqlcursor.execute('''
                        UPDATE options SET
                            savepath=?,
                            desktopsize=?,
                            filetype=?,
                            compression=?,
                            hour=?,
                            minute=?,
                            repeat=?
                        WHERE id=? ''', values)
        #update and close the database
        sqlconn.commit()
        sqlconn.close()
    
    def __init__(self):
        gtkbuilder = Gtk.Builder()
        gtkbuilder.add_from_file(GLADE_FILE)
        
        #glade objects
        self.prefs_dialog = gtkbuilder.get_object('prefs_dialog')
        self.version_label = gtkbuilder.get_object('version_label')
        self.about_dialog = gtkbuilder.get_object('about_dialog')
        self.savepath_filechooserbutton = gtkbuilder.get_object('savepath_filechooserbutton')
        self.starthour_spinbutton = gtkbuilder.get_object('starthour_spinbutton')
        self.startmin_spinbutton = gtkbuilder.get_object('startmin_spinbutton')
        self.repeat_none_radiobutton = gtkbuilder.get_object('repeat_none_radiobutton')
        self.repeat_min_radiobutton = gtkbuilder.get_object('repeat_min_radiobutton')
        self.repeat_hour_radiobutton = gtkbuilder.get_object('repeat_hour_radiobutton')
        self.repeat_day_radiobutton = gtkbuilder.get_object('repeat_day_radiobutton')
        self.repeat_week_radiobutton = gtkbuilder.get_object('repeat_week_radiobutton')
        self.png_radiobutton = gtkbuilder.get_object('png_radiobutton')
        self.jpg_radiobutton = gtkbuilder.get_object('jpg_radiobutton')
        self.jpgcompression_spinbutton = gtkbuilder.get_object('jpgcompression_spinbutton')
        self.enable_togglebutton = gtkbuilder.get_object('enable_togglebutton')
        self.desktopsize_comboboxtext_entry = gtkbuilder.get_object('desktopsize_comboboxtext_entry')
        
        signals = { 'on_prefs_dialog_destroy' : self.main_quit,
                    'on_about_menuitem_activate' : self.on_about_menu_activate,
                    'on_quit_menuitem_activate' : self.main_quit,
                    'on_about_menu_activate' : self.on_about_menu_activate,
                    'on_about_close_button_clicked' : self.on_about_dialog_delete_event,
                    'on_about_dialog_delete_event' : self.on_about_dialog_delete_event,
                    'on_enable_togglebutton_toggled' : self.on_enable_togglebutton_toggled
                     }
        gtkbuilder.connect_signals(signals)
        
        #cleanup left over PIDs and config files (possibly from a crash or logout)
        self.startupcleanup()

        #perform some initialization functions
        self.check_sqlitedb()
        self.read_configfile()

if __name__ == "__main__":
    pyscreenie = pyscreenie()
    Gtk.main()
    
